### ISSUE TITLE
Mob attack animation messes up sprite alignment for large mobs

### ISSUE THREAD

**Issue by SpadesNeil** [VOREStation/VOREStation#178]
#### Brief description of the issue

Mobs like the large snake and xeno empress are supposed to be adjusted to the center of the tile by the pixel_x variable so they are easier to understand where you're supposed to attack when you're a player.
#### What you expected to happen

After the attack animation bumping toward the target, the mob returns to the original position.
#### What actually happened

It resets its pixel_x axis to 0.
#### Steps to reproduce
1. Change the pixel alignment of any hostile mob.
2. Sick it on a target.
3. Note the sprite does not return to its original position.
#### Additional info:
- **Server Revision**: https://github.com/VOREStation/VOREStation/commit/849c30750d4ba1099d650c1abc9cf818c8fc4073
- **Anything else you may wish to add**: https://github.com/PolarisSS13/Polaris/issues/2352

**Comment by Arokha** [comment]
Can't use initial as that breaks dogborgs. Initial for dogborgs is 0 because they are /mob/living/silicon and that has x/y set to 0. Then nudged to -16 or whatever by their module.

I already fixed this for dogborgs by making it use values "old_x" and "old_y". Y'just need to set those on your mobs as well as pixel_x and pixel_y. Those are the values it'll return to when done with the attack animation.

**Comment by SpadesNeil** [comment]
Now I need to figure out where attack animations are handled.

**Comment by Arokha** [comment]
No I mean I already fixed this. You just need to set old_x and old_y on your mobs, in addition to pixel_x and pixel_y

**Comment by SpadesNeil** [comment]
OH, really? I just have to add those vars?

**Comment by SpadesNeil** [comment]
Alien empress is aligned wrongly. Will investigate later.

**Comment by SpadesNeil** [comment]
Confirmed that this is still broken in spite of adding old_x and old_y.

**Comment by SpadesNeil** [comment]
Re-opening because I discovered the problem.

New steps to reproduce:
1. Grab a large mob.
2. Release grab.
3. old_x and old_y are ignored.

**Comment by Arokha** [comment]
Is this still an issue?

**Comment by SpadesNeil** [comment]
I don't think anything has fixed it. I have to test it.

**Comment by Arokha** [comment]
If you find that it's broken, reopen this.
